name: Manual Run

on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'Candles limit'
        required: false
        default: '200'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python analyze.py
