# .github/workflows/run.yml
name: Binance Long-Term Analysis (Pages)

on:
  workflow_dispatch:
  schedule:
    - cron: "7 * * * *"  # щогодини +7 хвилин

# не допускаємо паралельних запусків цього ж воркфлоу
concurrency:
  group: btc-futures-analysis-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # жорстка межа на весь крок build
    env:
      CF_WORKER_BASE: ${{ secrets.CF_WORKER_BASE || vars.CF_WORKER_BASE || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (fast)
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --disable-pip-version-check requests pandas

      # analyze.py вже містить короткі таймаути/ретраї та дедлайни
      - name: Run analyzer (unbuffered logs)
        run: python -u analyze.py

      - name: Show artifact summary
        run: |
          ls -lah || true
          ls -lah public || true
          echo "---- report.json head ----"
          sed -n '1,120p' public/report.json || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write        # необхідно для деплою на Pages
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
