# .github/workflows/run.yml
name: Binance Long-Term Analysis (Pages)

on:
  workflow_dispatch:
  schedule:
    - cron: "7 * * * *"  # щогодини +7 хвилин

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install --upgrade pip
      - run: pip install requests pandas
      - run: python analyze.py
      - uses: actions/upload-pages-artifact@v3
        with: { path: ./public }

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
